create table if not exists public.playstation_products (
  id bigint generated by default as identity primary key,
  name text not null,
  family text not null check (family in ('ps4','ps5')),
  model text,
  storage text,
  condition text,
  price numeric(12,2) not null default 0,
  prev_price numeric(12,2),
  image text,
  stock_quantity integer not null default 1,
  is_available boolean not null default true,
  is_offer boolean not null default false,
  is_featured boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.playstation_products enable row level security;
drop policy if exists "public read available playstation products" on public.playstation_products;
create policy "public read available playstation products" on public.playstation_products for select using (is_available = true);
