"use client";
import { useEffect, useState } from "react";

type PS={id:number;name:string;family:"ps4"|"ps5";product_type?:"console"|"controller"|"accessory";model?:string|null;storage?:string|null;storage_options?:string[]|null;condition?:string|null;controller_connection?:string|null;controller_count?:number|null;details?:string|null;included_options?:string[]|null;modification_status?:"modified"|"unmodified"|null;modification_types?:string[]|null;price:number;prev_price?:number|null;image?:string|null;stock_quantity:number;is_available:boolean;is_offer:boolean;is_featured:boolean;order_note?:string|null;};
const GIFT_OPTIONS=["🎮 10 ألعاب هدية","🔌 وصلاتها / الكابلات","🛡️ كفالة 6 شهور"];
const MOD_OPTIONS=["CD","يوتيوب","Netflix","50 دقيقة"];
const empty:any={name:"",family:"ps5",product_type:"console",model:"",storage:"",storage_options:["1TB"],condition:"",controller_connection:"",controller_count:1,details:"",included_options:[],modification_status:"unmodified",modification_types:[],price:"",prev_price:"",image:"",stock_quantity:"1",is_available:true,is_offer:false,is_featured:false,order_note:""};
function storagePreset(family:string, model:string){ if(family==='ps4') return ['500GB','1TB']; const m=String(model||'').toLowerCase(); if(m.includes('slim')||m.includes('pro')) return ['1TB','2TB']; return ['1TB']; }
export default function PlaystationAdmin(){
 const [items,setItems]=useState<PS[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editing,setEditing]=useState<PS|null>(null),[form,setForm]=useState<any>(empty),[filter,setFilter]=useState("all"),[uploading,setUploading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const r=await fetch('/api/admin/playstation-products',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setItems(j.data||[]);else setError(j.error||'تعذر تحميل منتجات PlayStation');setLoading(false)};useEffect(()=>{void load()},[]);
 const upload=async(file:File)=>{setUploading(true);try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/digital-images',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'تعذر رفع الصورة');setForm((x:any)=>({...x,image:j.url}))}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الصورة')}finally{setUploading(false)}};
 const open=(p?:PS)=>{setEditing(p||null);const next=p?{...empty,...p,storage_options:p.storage_options||[p.storage||'1TB'].filter(Boolean),included_options:p.included_options||[],modification_types:p.modification_types||[],prev_price:p.prev_price??'',image:p.image||'',order_note:p.order_note||''}:{...empty,__new:true}; if(next.product_type!=='controller') next.storage_options=storagePreset(next.family,next.model); setForm(next)};
 const save=async()=>{setSaving(true);setError('');const payload={...form,price:Number(form.price||0),prev_price:form.prev_price===''?null:Number(form.prev_price),stock_quantity:Number(form.stock_quantity||0),storage_options:form.product_type==='controller'?[]:String(form.storage_options_text||form.storage_options?.join(',')||'').split(',').map((x:string)=>x.trim()).filter(Boolean),included_options:Array.isArray(form.included_options)?form.included_options:[],modification_types:Array.isArray(form.modification_types)?form.modification_types:[],controller_count:form.product_type==='accessory'?null:Number(form.controller_count||1)};delete payload.__new;delete payload.storage_options_text;const r=await fetch('/api/admin/playstation-products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing.id,...payload}:payload)});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'تعذر الحفظ');else{await load();setEditing(null);setForm({...empty})}setSaving(false)};
 const remove=async(p:PS)=>{if(!confirm(`حذف «${p.name}»؟`))return;const r=await fetch('/api/admin/playstation-products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id})});if(!r.ok){const j=await r.json().catch(()=>({}));setError(j.error||'تعذر الحذف');return}if(p.image)void fetch('/api/admin/digital-images',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:p.image})}).catch(()=>{});await load()};
 const isController=form.product_type==='controller';
 if(editing!==null||form.__new)return <section dir="rtl" className="space-y-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-blue">PLAYSTATION PRODUCTS</p><h2 className="text-2xl font-extrabold">{editing?'تعديل منتج PlayStation':'إضافة منتج PlayStation'}</h2></div><button onClick={()=>{setEditing(null);setForm({...empty})}} className="rounded-xl border border-line px-4 py-2 text-xs font-bold">رجوع</button></div>
 <div className="rounded-3xl border border-line bg-white p-5 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
 <label><span className="admin-field-label">نوع المنتج</span><select value={form.product_type||'console'} onChange={e=>setForm((x:any)=>({...x,product_type:e.target.value}))} className="admin-field"><option value="console">🎮 جهاز PlayStation</option><option value="controller">🕹️ قبضة تحكم</option><option value="accessory">🔌 ملحق PlayStation</option></select></label>
 <label><span className="admin-field-label">اسم المنتج</span><input value={form.name||''} onChange={e=>setForm((x:any)=>({...x,name:e.target.value}))} className="admin-field" placeholder="مثلاً PS5 Slim"/></label>
 <label><span className="admin-field-label">المنصة</span><select value={form.family} onChange={e=>{const family=e.target.value;const model=family==='ps5'?'PS5 FAT':'';setForm((x:any)=>({...x,family,model,storage_options:storagePreset(family,model)}))}} className="admin-field"><option value="ps5">PS5</option><option value="ps4">PS4</option></select></label>
 {isController?<label><span className="admin-field-label">موديل القبضة</span><input value={form.model||''} onChange={e=>setForm((x:any)=>({...x,model:e.target.value}))} className="admin-field"/></label>:<label><span className="admin-field-label">موديل الجهاز</span><select value={form.model||''} onChange={e=>{const model=e.target.value;setForm((x:any)=>({...x,model,storage_options:storagePreset(x.family,model)}))}} className="admin-field"><option value="">اختر الموديل</option>{form.family==='ps5'?<><option value="PS5 FAT">PS5 FAT</option><option value="PS5 Slim">PS5 Slim</option><option value="PS5 Pro">PS5 Pro</option></>:<><option value="PS4">PS4</option><option value="PS4 Slim">PS4 Slim</option><option value="PS4 Pro">PS4 Pro</option></>}</select></label>}
 {!isController&&<label><span className="admin-field-label">خيارات التخزين التي يختارها الزبون</span><div className="grid grid-cols-2 gap-2">{storagePreset(form.family,form.model).map((x:string)=><label key={x} className="flex items-center gap-2 rounded-xl border border-line bg-surface p-3 text-xs font-bold"><input type="checkbox" checked={(form.storage_options||[]).includes(x)} onChange={e=>setForm((v:any)=>({...v,storage_options:e.target.checked?[...(v.storage_options||[]),x]:(v.storage_options||[]).filter((z:string)=>z!==x)}))}/>{x}</label>)}</div><small className="mt-1 block text-[9px] text-ink-soft">PS4: 500GB أو 1TB • PS5 FAT: 1TB • PS5 Slim/Pro: 1TB أو 2TB</small></label>}
 {(isController||form.product_type==='console')&&<label><span className="admin-field-label">محتويات المنتج</span><select value={form.controller_count||1} onChange={e=>setForm((x:any)=>({...x,controller_count:Number(e.target.value)}))} className="admin-field"><option value="1">🕹️ قبضة أساسية</option><option value="2">🕹️🕹️ قبضتين</option></select></label>}
 {isController&&<><label><span className="admin-field-label">إعدادات الاتصال</span><input value={form.controller_connection||''} onChange={e=>setForm((x:any)=>({...x,controller_connection:e.target.value}))} className="admin-field" placeholder="لاسلكي • USB • Bluetooth"/></label></>}
 <label><span className="admin-field-label">الحالة</span><input value={form.condition||''} onChange={e=>setForm((x:any)=>({...x,condition:e.target.value}))} className="admin-field" placeholder="جديد / مستعمل / شبه جديد"/></label><label><span className="admin-field-label">سعر البيع $</span><input type="number" value={form.price??''} onChange={e=>setForm((x:any)=>({...x,price:e.target.value}))} className="admin-field"/></label><label><span className="admin-field-label">السعر السابق $</span><input type="number" value={form.prev_price??''} onChange={e=>setForm((x:any)=>({...x,prev_price:e.target.value}))} className="admin-field"/></label>
 </div>
 <label className="block mt-4"><span className="admin-field-label">تفاصيل المنتج</span><textarea rows={4} value={form.details||''} onChange={e=>setForm((x:any)=>({...x,details:e.target.value}))} className="admin-field"/></label>
 <label className="block mt-4"><span className="admin-field-label">الملاحظة عند طلب المنتج</span><textarea rows={3} value={form.order_note||''} onChange={e=>setForm((x:any)=>({...x,order_note:e.target.value}))} className="admin-field" placeholder="ملاحظة مهمة تظهر للزبون أثناء الطلب"/></label>
 {!isController&&<div className="mt-5 rounded-2xl bg-surface p-4"><b className="text-sm">الجهاز معدل؟</b><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border border-line bg-white p-3 text-xs font-bold"><input type="radio" name="modstatus" checked={form.modification_status!=='modified'} onChange={()=>setForm((x:any)=>({...x,modification_status:'unmodified',modification_types:[]}))}/> غير معدل</label><label className="flex items-center gap-2 rounded-xl border border-line bg-white p-3 text-xs font-bold"><input type="radio" name="modstatus" checked={form.modification_status==='modified'} onChange={()=>setForm((x:any)=>({...x,modification_status:'modified'}))}/> معدل</label></div>{form.modification_status==='modified'&&<><p className="mt-3 text-xs font-bold text-ink-soft">نوع التعديل — اختر واحد أو أكثر</p><div className="mt-2 grid gap-2 sm:grid-cols-4">{MOD_OPTIONS.map(x=><label key={x} className="flex items-center gap-2 rounded-xl border border-line bg-white p-3 text-xs font-bold"><input type="checkbox" checked={form.modification_types?.includes(x)||false} onChange={e=>setForm((v:any)=>({...v,modification_types:e.target.checked?[...(v.modification_types||[]),x]:(v.modification_types||[]).filter((z:string)=>z!==x)}))}/>{x}</label>)}</div></>}</div>}
 <div className="mt-5 rounded-2xl bg-surface p-4"><b className="text-sm">🎁 المحتويات والهدايا</b><div className="mt-3 grid gap-2 sm:grid-cols-3">{GIFT_OPTIONS.map(x=><label key={x} className="flex items-center gap-2 rounded-xl border border-line bg-white p-3 text-xs font-bold"><input type="checkbox" checked={form.included_options?.includes(x)||false} onChange={e=>setForm((v:any)=>({...v,included_options:e.target.checked?[...(v.included_options||[]),x]:(v.included_options||[]).filter((z:string)=>z!==x)}))}/>{x}</label>)}</div></div>
 <div className="mt-5 rounded-2xl bg-surface p-4"><div className="flex items-center justify-between"><b className="text-sm">صورة المنتج</b><label className="cursor-pointer rounded-xl bg-blue px-4 py-2.5 text-xs font-bold text-white">{uploading?'جاري الرفع...':'📸 اختيار صورة'}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></div>{form.image&&<img src={form.image} alt="" className="mt-4 h-52 w-full rounded-2xl object-contain bg-white"/>}</div>
 <div className="mt-4 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.is_available} onChange={e=>setForm((x:any)=>({...x,is_available:e.target.checked}))}/> متوفر</label><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.is_offer} onChange={e=>setForm((x:any)=>({...x,is_offer:e.target.checked}))}/> عرض</label><label className="flex items-center gap-2"><input type="checkbox" checked={!!form.is_featured} onChange={e=>setForm((x:any)=>({...x,is_featured:e.target.checked}))}/> مميز</label></div></div><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-blue px-6 py-3 text-sm font-bold text-white">{saving?'جاري الحفظ...':'حفظ المنتج'}</button>{error&&<p className="text-sm text-red-600">{error}</p>}</section>;
 const visible=filter==='all'?items:filter==='controller'?items.filter(x=>x.product_type==='controller'):items.filter(x=>x.family===filter&&x.product_type!=='controller');
 return <section dir="rtl" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-blue">PLAYSTATION</p><h2 className="text-xl font-extrabold">منتجات PlayStation</h2><p className="mt-1 text-xs text-ink-soft">أجهزة، قبضات وملحقات مع خيارات الزبون أثناء الطلب.</p></div><button onClick={()=>open()} className="rounded-xl bg-blue px-4 py-2.5 text-xs font-bold text-white">+ إضافة جهاز / قبضة</button></div><div className="flex gap-2 overflow-x-auto rounded-2xl bg-surface p-1"><button onClick={()=>setFilter('all')} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-bold ${filter==='all'?'bg-white text-blue shadow-sm':'text-ink-soft'}`}>الكل</button><button onClick={()=>setFilter('ps5')} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-bold ${filter==='ps5'?'bg-white text-blue shadow-sm':'text-ink-soft'}`}>PS5</button><button onClick={()=>setFilter('ps4')} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-bold ${filter==='ps4'?'bg-white text-blue shadow-sm':'text-ink-soft'}`}>PS4</button><button onClick={()=>setFilter('controller')} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-bold ${filter==='controller'?'bg-white text-blue shadow-sm':'text-ink-soft'}`}>🕹️ القبضات</button></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</div>}{loading?<p className="text-sm text-ink-soft">جاري التحميل...</p>:<div className="grid gap-4 lg:grid-cols-2">{visible.map(p=><article key={p.id} className="rounded-2xl border border-line bg-white p-4 shadow-sm"><div className="flex gap-4"><div className="h-28 w-28 shrink-0 overflow-hidden rounded-xl bg-surface">{p.image?<img src={p.image} alt="" className="h-full w-full object-contain"/>:<div className="flex h-full items-center justify-center font-black text-blue">{p.family.toUpperCase()}</div>}</div><div className="min-w-0 flex-1"><span className="text-[10px] font-bold text-blue">{p.product_type==='controller'?`🕹️ قبضة ${p.family.toUpperCase()}`:p.family.toUpperCase()}</span><h3 className="mt-1 font-bold">{p.name}</h3><p className="mt-1 text-xs text-ink-soft">{[p.model,p.product_type==='controller'?p.controller_connection:p.storage,p.condition].filter(Boolean).join(' · ')}</p><b className="mt-2 block">${Number(p.price).toFixed(0)}</b>{p.modification_status==='modified'&&<span className="mt-2 inline-flex rounded-full bg-orange-50 px-2 py-1 text-[9px] font-bold text-orange-700">معدل: {(p.modification_types||[]).join(' • ')}</span>}</div></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>open(p)} className="rounded-xl bg-blue px-4 py-2.5 text-xs font-bold text-white">تعديل</button><button onClick={()=>void remove(p)} className="rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-xs font-bold text-red-600">حذف</button></div></article>)}</div>}</section>;
}
