"use client";import{useEffect,useMemo,useState}from'react';
type Notice={id:string;title:string;body:string;href?:string|null;kind:string;target_user_id?:string|null;created_at:string};
export default function NotificationsPage(){const[items,setItems]=useState<Notice[]>([]);const[readIds,setReadIds]=useState<string[]>([]);const[form,setForm]=useState({title:'Bkkari Tech — ',body:'',href:'/',kind:'general',target_user_id:''});const[saving,setSaving]=useState(false);const[msg,setMsg]=useState('');const[search,setSearch]=useState('');const[checked,setChecked]=useState<string[]>([]);
 async function load(){const r=await fetch('/api/admin/notifications',{cache:'no-store'});const j=await r.json();if(r.ok){setItems(j.data||[]);setReadIds(j.readIds||[]);setChecked([])}}useEffect(()=>{void load()},[]);const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return items;return items.filter(n=>[n.title,n.body,n.kind,n.target_user_id].some(v=>String(v??'').toLowerCase().includes(q)))},[items,search]);
 async function send(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg('');const r=await fetch('/api/admin/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,target_user_id:form.target_user_id||null})});const j=await r.json();setSaving(false);if(!r.ok){setMsg(j.error||'تعذر الإرسال');return}setMsg(`تم نشر الإشعار ✓${j.pushSent?` وتم إرسال ${j.pushSent} Push`:''}`);setForm({title:'Bkkari Tech — ',body:'',href:'/',kind:'general',target_user_id:''});void load()}
 function toggle(id:string){setChecked(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}function all(){setChecked(checked.length===filtered.length&&filtered.length?[]:filtered.map(n=>n.id))}
 async function mark(){const ids=checked.length?checked:filtered.map(n=>n.id);if(!ids.length)return;await fetch('/api/admin/notifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});setReadIds(x=>Array.from(new Set([...x,...ids])));setChecked([])}
 async function del(){const ids=checked.length?checked:[];if(!confirm(ids.length?`حذف ${ids.length} إشعار؟\n\nنعم = حذف نهائي\nلا = إلغاء`:'حذف كل الإشعارات الظاهرة؟\n\nنعم = حذف نهائي\nلا = إلغاء'))return;const r=await fetch('/api/admin/notifications',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify(ids.length?{ids}:{})});const j=await r.json().catch(()=>({}));if(!r.ok)return alert(j.error||'تعذر الحذف');void load()}
 return <main dir="rtl" className="admin-page"><div className="admin-hero"><div><span>IBRAHIM BAKKARI • NOTIFICATIONS</span><h1>مركز الإشعارات 🔔</h1></div><div className="admin-hero-orb">🔔</div></div><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={send} className="admin-card"><h2>إشعار جديد</h2><div className="mt-5 space-y-3"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="العنوان"/><textarea required rows={4} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="اكتب الرسالة..."/><div className="grid gap-3 sm:grid-cols-2"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="general">عام</option><option value="offer">🔥 عروض</option><option value="order">📦 طلبات</option><option value="product">💻 منتجات</option></select><input value={form.href} onChange={e=>setForm({...form,href:e.target.value})} placeholder="الرابط /offers"/></div><input value={form.target_user_id} onChange={e=>setForm({...form,target_user_id:e.target.value})} placeholder="معرّف المستخدم (اختياري)"/><button disabled={saving} className="w-full rounded-2xl bg-blue px-5 py-3 font-bold text-white disabled:opacity-60">{saving?'جاري النشر...':'نشر الإشعار 🔔'}</button>{msg&&<p className="rounded-xl bg-surface p-3 text-xs text-ink-soft">{msg}</p>}</div></form>
 <section className="admin-card"><div className="flex flex-col gap-3"><div className="flex items-center justify-between"><div><h2>الإشعارات</h2></div><button onClick={()=>void load()} className="rounded-xl border border-line px-3 py-2 text-xs font-bold">تحديث</button></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔎 ابحث بالإشعار أو النص..."/><div className="flex flex-wrap gap-2"><button onClick={all} className="rounded-xl border border-line px-3 py-2 text-xs font-bold">{checked.length===filtered.length&&filtered.length?'إلغاء تحديد الكل':'تحديد الكل'}</button><button onClick={()=>void mark()} className="rounded-xl border border-blue/20 bg-blue/10 px-3 py-2 text-xs font-bold text-blue">تحديد كمقروء</button><button onClick={()=>void del()} className="rounded-xl bg-red-600 px-3 py-2 text-xs font-bold text-white">{checked.length?'حذف المحدد':'حذف الكل'}</button></div></div><div className="mt-5 space-y-3">{filtered.length?filtered.map(n=><div key={n.id} dir="rtl" className={`notification-admin-row ${readIds.includes(n.id)?'opacity-70':'ring-1 ring-orange/20'}`}><input type="checkbox" checked={checked.includes(n.id)} onChange={()=>toggle(n.id)} className="notification-admin-check h-4 w-4"/><span className="notification-admin-icon shrink-0">{n.kind==='offer'?'🔥':n.kind==='order'?'📦':n.kind==='product'?'💻':'🔔'}</span><div className="notification-admin-content"><b>{n.title}</b><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('ar-SY')} · {n.target_user_id?'مستخدم محدد':'الجميع'} · {readIds.includes(n.id)?'مقروء':'جديد'}</small></div></div>):<div className="rounded-2xl bg-surface p-8 text-center text-sm text-ink-soft">ما في نتائج.</div>}</div></section></div></main>
}
