"use client";
import{useEffect,useMemo,useState}from"react";import DeleteConfirm from"@/app/DeleteConfirm";
const statuses=["جديد","قيد التواصل","تم الاتفاق","قيد التنفيذ","مكتمل","ملغي"];
export default function RequestsPage(){const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[checked,setChecked]=useState<number[]>([]);const[confirmOpen,setConfirmOpen]=useState(false);
async function load(){setLoading(true);const r=await fetch("/api/admin/web-requests");const j=await r.json();setItems(j.data||[]);setChecked([]);setLoading(false)}useEffect(()=>{void load()},[]);
const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return items;return items.filter(i=>[i.id,i.name,i.phone,i.email,i.website_type,i.status,i.budget].some(v=>String(v??"").toLowerCase().includes(q)))},[items,search]);
function toggle(id:number){setChecked(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}function all(){setChecked(checked.length===filtered.length&&filtered.length?[]:filtered.map(i=>i.id))}
async function del(){if(!checked.length)return;setConfirmOpen(true)}async function performDelete(){const ids=[...checked];setConfirmOpen(false);const r=await fetch("/api/admin/web-requests",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({ids})});const j=await r.json().catch(()=>({}));if(!r.ok)return alert(j.error||"تعذر الحذف");setItems(x=>x.filter(i=>!ids.includes(i.id)));setChecked([])}
async function setStatus(id:number,status:string){const r=await fetch("/api/admin/web-requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(r.ok)setItems(x=>x.map(i=>i.id===id?{...i,status}:i))}
return <div className="space-y-6" dir="rtl"><div><p className="text-xs font-semibold text-blue">طلبات تطوير المواقع</p><h1 className="mt-1 text-2xl font-bold">طلبات جديدة من المتجر</h1></div><div className="admin-card"><div className="flex flex-col gap-3 sm:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔎 ابحث بالاسم، الهاتف، الإيميل، نوع الموقع، الحالة..." className="flex-1"/><button onClick={all} className="rounded-xl border border-line px-4 py-2 text-xs font-bold">{checked.length===filtered.length&&filtered.length?"إلغاء تحديد الكل":"تحديد الكل"}</button>{checked.length>0&&<button onClick={()=>void del()} className="rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white">حذف المحدد ({checked.length})</button>}</div></div>{loading?<p className="text-sm text-ink-soft">جاري التحميل...</p>:filtered.length===0?<div className="rounded-2xl border border-line bg-white p-8 text-center text-sm text-ink-soft">ما في نتائج.</div>:<div className="space-y-3">{filtered.map(i=><article key={i.id} className="rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="flex gap-3"><input type="checkbox" checked={checked.includes(i.id)} onChange={()=>toggle(i.id)} className="mt-1 h-4 w-4"/><div className="min-w-0 flex-1"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{i.name}</h2><span className="rounded-full bg-blue/10 px-2.5 py-1 text-xs font-semibold text-blue">{i.website_type}</span></div><p className="mt-1 text-sm text-ink-soft">{i.phone}{i.email?` · ${i.email}`:""}</p></div><time className="text-xs text-ink-soft">{new Date(i.created_at).toLocaleString("ar-SY")}</time></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info l="الميزانية" v={i.budget||"غير محددة"}/><Info l="رابط حالي" v={i.current_website_url||"لا يوجد"}/><Info l="الحالة" v={i.status}/></div><div className="mt-4 rounded-xl bg-surface p-4 text-sm leading-7">{i.project_details||"بدون تفاصيل إضافية"}</div><div className="mt-4 flex flex-wrap gap-2">{statuses.map(st=><button key={st} onClick={()=>setStatus(i.id,st)} className={`rounded-full px-3 py-2 text-xs font-semibold ${i.status===st?"bg-blue text-white":"border border-line bg-white text-ink-soft"}`}>{st}</button>)}</div></div></div></article>)}</div>}<DeleteConfirm open={confirmOpen} title={`حذف ${checked.length} طلب موقع؟ هذا الإجراء نهائي.`} onYes={()=>void performDelete()} onNo={()=>setConfirmOpen(false)}/></div>}
function Info({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-surface p-3"><p className="text-[11px] text-ink-soft">{l}</p><p className="mt-1 break-words text-sm font-semibold">{v}</p></div>}
