"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/app/lib/supabase-browser";
import AdminPushNotifications from "@/app/AdminPushNotifications";

export default function AccountPage(){
 const supabase=createClient();
 const [user,setUser]=useState<any>(null); const [name,setName]=useState(""); const [phone,setPhone]=useState("");
 const [saving,setSaving]=useState(false); const [backupBusy,setBackupBusy]=useState(false); const [file,setFile]=useState<File|null>(null); const [restoreBusy,setRestoreBusy]=useState(false); const [backupMsg,setBackupMsg]=useState(""); const [avatarBusy,setAvatarBusy]=useState(false); const [avatarProgress,setAvatarProgress]=useState(0); const [msg,setMsg]=useState("");
 const [notify,setNotify]=useState({state:"checking",detail:"جاري فحص الإشعارات..."});
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser(); const u=data.user; setUser(u); setName(u?.user_metadata?.full_name||""); setPhone(u?.user_metadata?.phone||"");
   const supported="Notification" in window && "serviceWorker" in navigator;
   if(!supported)setNotify({state:"error",detail:"المتصفح لا يدعم إشعارات Push"});
   else if(Notification.permission!=="granted")setNotify({state:"error",detail:Notification.permission==="denied"?"الإشعارات موقوفة من إعدادات المتصفح":"الإشعارات غير مفعلة"});
   else {try{const regs=await navigator.serviceWorker.getRegistrations(); const ok=regs.some(r=>r.active?.scriptURL.endsWith("/admin-sw.js")); setNotify(ok?{state:"ok",detail:"الإشعارات تعمل بشكل طبيعي"}:{state:"error",detail:"خدمة الإشعارات غير شغالة"})}catch{setNotify({state:"error",detail:"تعذر فحص خدمة الإشعارات"})}}
 })()},[supabase]);
 function urlBase64ToUint8Array(base64String:string){const padding="=".repeat((4-(base64String.length%4))%4);const rawData=window.atob((base64String+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...rawData].map(c=>c.charCodeAt(0)))}
 async function save(){setSaving(true);setMsg(""); const {error}=await supabase.auth.updateUser({data:{full_name:name,phone}}); if(error)setMsg(error.message); else setMsg("تم حفظ معلومات الحساب ✓"); setSaving(false)}
 async function backup(){setBackupBusy(true);setBackupMsg("");try{const r=await fetch("/api/admin/backup",{cache:"no-store"});if(!r.ok)throw new Error("تعذر إنشاء النسخة");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`bkkari-tech-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setBackupMsg("تم حفظ النسخة الاحتياطية ✓")}catch(e:any){setBackupMsg(e.message||"تعذر إنشاء النسخة")}finally{setBackupBusy(false)}}
 async function restore(){if(!file||restoreBusy)return;if(!confirm("استرجاع النسخة سيستبدل البيانات المطابقة الموجودة حالياً. متابعة؟"))return;setRestoreBusy(true);setBackupMsg("");try{const f=new FormData();f.append("file",file);const r=await fetch("/api/admin/backup",{method:"POST",body:f});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"تعذر الاسترجاع");setBackupMsg("تم استرجاع النسخة بنجاح ✓")}catch(e:any){setBackupMsg(e.message||"تعذر الاسترجاع")}finally{setRestoreBusy(false)}}
 async function avatar(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]; if(!f||!user)return; if(!/^image\/(jpeg|png|webp|avif)$/.test(f.type))return setMsg("صيغة الصورة غير مدعومة"); if(f.size>10*1024*1024)return setMsg("الصورة أكبر من 10MB"); setAvatarBusy(true);setAvatarProgress(0);setMsg("");
   try{const path=`${user.id}/admin-${Date.now()}.${f.name.split('.').pop()||'jpg'}`; const xhr=new XMLHttpRequest(); const result=await new Promise<any>((resolve,reject)=>{xhr.upload.onprogress=e=>{if(e.lengthComputable)setAvatarProgress(Math.round(e.loaded/e.total*100))};xhr.onload=async()=>{if(xhr.status<200||xhr.status>=300)return reject(new Error('تعذر رفع الصورة')); let j:any={}; try{j=JSON.parse(xhr.responseText||'{}')}catch{} if(xhr.status<200||xhr.status>=300)return reject(new Error(j.error||'تعذر رفع الصورة')); resolve(j.url)};xhr.onerror=()=>reject(new Error('Failed to fetch'));xhr.open('POST','/api/admin/account/avatar-upload');xhr.setRequestHeader('x-avatar-path',path);xhr.setRequestHeader('x-avatar-type',f.type);xhr.send(f)}); 
     const {error}=await supabase.auth.updateUser({data:{avatar_url:result}}); if(error)throw error; setUser((u:any)=>({...u,user_metadata:{...u.user_metadata,avatar_url:result}}));setMsg('تم تغيير صورة الحساب ✓');setAvatarProgress(100)
   }catch(e){setMsg(e instanceof Error?e.message:'تعذر رفع الصورة')}finally{setAvatarBusy(false);e.target.value=''}
 }
 const Avatar=()=>user?.user_metadata?.avatar_url?<img src={user.user_metadata.avatar_url} alt="صورة الحساب" className="h-24 w-24 rounded-3xl object-cover ring-2 ring-blue/20"/>:<div className="grid h-24 w-24 place-items-center rounded-3xl bg-blue/10 text-3xl font-black text-blue">{(name||user?.email||'A').slice(0,1).toUpperCase()}</div>;
 return <main dir="rtl" className="admin-page space-y-6"><section className="admin-hero"><div><span>حساب الإدارة</span><h1>الحساب 👤</h1></div><div className="admin-hero-orb">👤</div></section>
 <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="admin-card"><h2>معلومات الحساب</h2><div className="mt-5 flex flex-wrap items-center gap-5"><Avatar/><div><label className="inline-flex cursor-pointer rounded-xl bg-blue px-4 py-2.5 text-xs font-bold text-white">{avatarBusy?'جاري الرفع...':'تغيير صورة الحساب'}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={avatar} className="hidden"/></label>{avatarBusy&&<UploadProgress value={avatarProgress} label="رفع صورة الحساب"/>}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-ink-soft">اسم الإدارة</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span className="mb-1 block text-xs font-bold text-ink-soft">رقم الهاتف</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><label className="mt-4 block"><span className="mb-1 block text-xs font-bold text-ink-soft">البريد الإلكتروني</span><input value={user?.email||''} readOnly/></label><label className="mt-4 block"><span className="mb-1 block text-xs font-bold text-ink-soft">معرّف الحساب</span><input value={user?.id||''} readOnly/></label><button onClick={save} disabled={saving} className="mt-5 rounded-xl bg-blue px-5 py-3 text-sm font-bold text-white">{saving?'جاري الحفظ...':'حفظ معلومات الحساب'}</button>{msg&&<p className="mt-3 rounded-xl bg-surface p-3 text-xs text-ink-soft">{msg}</p>}</section>
 <section className="space-y-4"><Status title="الإشعارات" data={notify} action={<div className="mt-4"><AdminPushNotifications/></div>}/><section className="admin-card"><span className="section-kicker">DATA SAFETY</span><h2>النسخ الاحتياطي</h2><p className="mt-2 text-xs leading-6 text-ink-soft">احفظ نسخة من بيانات المتجر قبل التعديلات الكبيرة، أو استرجع نسخة محفوظة.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void backup()} disabled={backupBusy} className="admin-action">{backupBusy?'جاري التجهيز...':'⬇️ حفظ نسخة احتياطية'}</button><label className="admin-action cursor-pointer">📁 اختيار نسخة<input type="file" accept="application/json,.json" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button onClick={()=>void restore()} disabled={!file||restoreBusy} className="admin-action admin-action-dark">{restoreBusy?'جاري الاسترجاع...':'↩️ استرجاع النسخة'}</button></div>{file&&<p className="mt-3 text-xs font-bold text-blue">الملف: {file.name}</p>}{backupMsg&&<p className="mt-3 text-xs font-bold text-ink-soft">{backupMsg}</p>}</section></section></div></main>
}
function Status({title,data,action}:{title:string;data:any;action?:React.ReactNode}){const ok=data.state==='ok';return <div className="admin-card"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-extrabold">{title}</h2><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${data.state==='checking'?'bg-white text-ink-soft':ok?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{data.state==='checking'?'جاري الفحص':ok?'يعمل':'مشكلة'}</span></div><p className="mt-3 text-xs leading-6 text-ink-soft">{data.detail}</p>{action}</div>}
function UploadProgress({value,label}:{value:number;label:string}){return <div className="mt-3 min-w-[220px]"><div className="flex justify-between text-[10px] font-bold text-ink-soft"><span>{label}</span><span>{value}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue transition-all" style={{width:`${value}%`}}/></div></div>}
