"use client";
import {useEffect,useState} from "react";
export default function AdminsPage(){
 const [admins,setAdmins]=useState<any[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 async function load(){setLoading(true);const r=await fetch('/api/admin/admins',{cache:'no-store'});const j=await r.json();if(r.ok)setAdmins(j.admins||[]);else setMsg(j.error||'تعذر التحميل');setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg('');const r=await fetch('/api/admin/admins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name})});const j=await r.json();setMsg(r.ok?j.message:(j.error||'تعذر الإضافة'));if(r.ok){setEmail('');setName('');load()}setSaving(false)}
 async function toggle(a:any){const r=await fetch('/api/admin/admins',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,is_active:!a.is_active})});if(r.ok)load();else{const j=await r.json();setMsg(j.error||'تعذر التعديل')}}
 return <div className="admin-page space-y-6"><div className="admin-hero"><div><span>إدارة الفريق</span><h1>المشرفون وصلاحيات الإدارة</h1></div><div className="admin-hero-orb">🛡️</div></div>
 <div className="grid gap-5 lg:grid-cols-[1fr_1.35fr]"><form onSubmit={add} className="admin-card"><h2>إضافة مشرف جديد</h2><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المشرف"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com"/></div><button disabled={saving} className="mt-4 w-full rounded-2xl bg-blue px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?'جاري الإضافة...':'إرسال دعوة وإضافة المشرف'}</button>{msg&&<p className="mt-3 rounded-xl bg-surface p-3 text-xs font-semibold text-ink-soft">{msg}</p>}</form>
 <section className="admin-card"><h2>الحسابات الإدارية</h2>{loading?<p className="mt-5 text-sm text-ink-soft">جاري التحميل...</p>:<div className="mt-5 space-y-3">{admins.map(a=><div key={a.id} className="admin-user-row"><div className="admin-user-avatar">{a.name?.slice(0,1)||'A'}</div><div className="min-w-0 flex-1"><b>{a.name||'مشرف'}</b><small>{a.email}</small></div><span className={a.is_active?'admin-status on':'admin-status'}>{a.is_active?'نشط':'متوقف'}</span>{a.id!=='primary'&&<button onClick={()=>toggle(a)} className="admin-small-btn">{a.is_active?'تعطيل':'تفعيل'}</button>}</div>)}</div>}</section></div></div>
}
