"use client";
import {useEffect,useState} from "react";
import type { ReactNode } from "react";
import {createClient} from "@/app/lib/supabase-browser";

type AnySettings=Record<string,any>;
const defaults={
 contact:{phone:"0936426605",whatsapp:"963936426605",telegram:"@NexCode9",facebook:"https://www.facebook.com/share/1BZU7LUd2o/",email:"ibrahimbkkari51@gmail.com"},
 delivery:{title:"التوصيل والشحن",intro:"منوصل طلباتك لباب المنزل، والشحن متاح للمحافظات السورية حسب المحافظة.",home:"توصيل لباب المنزل — مننسق معك العنوان قبل التسليم.",governorates:"شحن لكل المحافظات الفعالة بالموقع، وتكلفة الشحن ومدة الوصول بتختلف حسب المحافظة.",note:"للطلبات الكبيرة أو خدمات البرمجة، مننسق التفاصيل معك بشكل مباشر."},
 terms:{title:"الشروط والأحكام",body:"باستخدام Bkkari Tech، يوافق المستخدم على تقديم معلومات صحيحة عند إنشاء الحساب أو الطلب، وعلى مراجعة تفاصيل المنتج والسعر قبل تأكيد الطلب."},
 returns:{title:"الاستبدال والاسترجاع",body:"يتم فحص طلبات الاستبدال والاسترجاع حسب حالة المنتج وسبب الطلب. يجب التواصل مع الدعم بأسرع وقت عند وجود مشكلة أو عيب."},
 privacy:{title:"سياسة الخصوصية",body:"نستخدم معلومات الحساب والطلب مثل الاسم والبريد ورقم الهاتف والعنوان لتنفيذ الطلب والتواصل مع العميل."},
 storefront_notices:[{id:"delivery",title:"شحن لجميع المحافظات",text:"مننسق معك العنوان وموعد التسليم حسب المحافظة.",icon:"🚚"},{id:"digital",title:"الخدمات الرقمية",text:"شحن ألعاب وبطاقات وخدمات رقمية بسرعة.",icon:"⚡"},{id:"support",title:"دعم سريع",text:"إذا احتجت مساعدة، تواصل معنا قبل الطلب أو بعده.",icon:"🎧"}],
faq:{items:[{q:"كيف بطلب لابتوب؟",a:"اختار الجهاز وأضفه للسلة وكمل بيانات الطلب."},{q:"كيف بيصير التوصيل؟",a:"مننسق معك العنوان وتفاصيل الشحن حسب المحافظة."},{q:"كيف بتتبع طلبي؟",a:"من صفحة تتبع الطلب أدخل رقم الطلب ورقم الهاتف."}]},
 wallet_payment:{method:"الدفع عند الاستلام أو المحفظة",account_name:"",account_number:"",image_url:"",note:"طرق الدفع المتاحة: المحفظة أو الدفع عند الاستلام."},
 wallet_topup:{mode:"direct_contact",title:"شحن مباشر للمحفظة",note:"لشحن المحفظة، تواصل مع الإدارة عبر واتساب أو الدعم."},
 rewards:{enabled:true,points_per_dollar:1,referrer_points:100,new_user_points:50,redemption_note:"كل 100 نقطة = 1$ رصيد خصم عند تطبيق النظام من الإدارة."},
 storefront_media:{hero:["/catalog/hero-laptop.png","/catalog/hero-gaming.png","/catalog/hero-playstation.png","/catalog/hero-digital.png","/catalog/hero-web.png"],categories:{business:"/catalog/cat-business.png",gaming:"/catalog/cat-gaming.png",desktop:"/catalog/cat-desktop.png",playstation:"/catalog/cat-playstation.png",digital:"/catalog/cat-digital.png",accessories:"/catalog/cat-accessories.png",web:"/catalog/cat-web.png",offers:"/catalog/cat-offers.png"},promos:{playstation:"/catalog/promo-playstation.png",digital:"/catalog/promo-digital.png",web:"/catalog/promo-web.png",desktop:"/catalog/promo-desktop.png"},playstation:"/catalog/playstation-banner.png",playstation_filters:{all:"/catalog/cat-playstation.png",ps4:"/catalog/ps4-circle.png",ps5:"/catalog/ps5-circle.png","ps4-controller":"/catalog/controller-ps4-circle.png","ps5-controller":"/catalog/controller-ps5-circle.png"},pc_builder:"/catalog/pc-builder.png",laptop_brand_logos:{}}
};
const DEFAULT_LAPTOP_BRAND_LOGOS:Record<string,string>={Apple:"/catalog/brands/apple.svg",ASUS:"https://cdn.simpleicons.org/asus/0F2A4A",Lenovo:"https://cdn.simpleicons.org/lenovo/0F2A4A",Dell:"https://cdn.simpleicons.org/dell/0F2A4A",HP:"https://cdn.simpleicons.org/hp/0F2A4A",Acer:"https://cdn.simpleicons.org/acer/0F2A4A",MSI:"https://cdn.simpleicons.org/msi/0F2A4A",Microsoft:"https://cdn.simpleicons.org/microsoft/0F2A4A",Samsung:"https://cdn.simpleicons.org/samsung/0F2A4A",LG:"https://cdn.simpleicons.org/lg/0F2A4A",Razer:"https://cdn.simpleicons.org/razer/0F2A4A",Huawei:"https://cdn.simpleicons.org/huawei/0F2A4A",Gigabyte:"https://cdn.simpleicons.org/gigabyte/0F2A4A",Alienware:"https://cdn.simpleicons.org/alienware/0F2A4A",Toshiba:"https://cdn.simpleicons.org/toshiba/0F2A4A",VAIO:"https://cdn.simpleicons.org/vaio/0F2A4A",Dynabook:"https://cdn.simpleicons.org/dynabook/0F2A4A",Xiaomi:"https://cdn.simpleicons.org/xiaomi/0F2A4A",Framework:"https://cdn.simpleicons.org/framework/0F2A4A",Chuwi:"https://cdn.simpleicons.org/chuwi/0F2A4A",Medion:"https://cdn.simpleicons.org/medion/0F2A4A"};
const tabs=["التواصل","صور الواجهة","شريط الإعلانات","الشحن","الأسئلة الشائعة","الشروط","الاستبدال","الخصوصية","الدفع","شحن المحفظة","النقاط"] as const;
export default function SettingsPage(){const s=createClient();const [tab,setTab]=useState<typeof tabs[number]>("التواصل");const [cfg,setCfg]=useState<AnySettings>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");
useEffect(()=>{
  fetch("/api/admin/site-settings").then(r=>r.json()).then(j=>{
    const incoming=j.settings||{};
    const media=incoming.storefront_media||{};
    const hero=Array.isArray(media.hero)?media.hero.slice(0,5):[];
    while(hero.length<5) hero.push(defaults.storefront_media.hero[hero.length]||"");
    setCfg(x=>({...x,...incoming,storefront_media:{...defaults.storefront_media,...media,hero,laptop_brand_logos:{...defaults.storefront_media.laptop_brand_logos,...(media.laptop_brand_logos||{})}}}));
  }).finally(()=>setLoading(false));
},[]);
async function save(key:string){setSaving(true);setMsg("");const r=await fetch("/api/admin/site-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key,value:cfg[key]})});setSaving(false);setMsg(r.ok?"تم الحفظ ✓":(await r.json()).error||"تعذر الحفظ")}
async function uploadPayment(file:File){const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`shamcash-${Date.now()}.${ext}`;const up=await s.storage.from("payment-assets").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMsg("تعذر رفع الصورة. تأكد من صلاحيات bucket الدفع.");return}const {data}=s.storage.from("payment-assets").getPublicUrl(path);setCfg((x:any)=>({...x,wallet_payment:{...x.wallet_payment,image_url:data.publicUrl}}));}async function uploadStorefrontImage(file:File,current:any,setter:(v:any)=>void){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/admin/digital-images",{method:"POST",body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"تعذر رفع الصورة");setter(j.url);return j.url}
async function deleteStorefrontImage(path:string){const next=structuredClone(cfg.storefront_media||defaults.storefront_media);const parts=path.split(".");let cur:any=next;for(let i=0;i<parts.length-1;i++)cur=cur?.[parts[i]];const oldUrl=cur?.[parts.at(-1)!];if(typeof oldUrl==="string"&&oldUrl){try{await fetch("/api/admin/digital-images",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:oldUrl})})}catch{}}if(Array.isArray(cur)){cur[Number(parts.at(-1))]=null}else cur[parts.at(-1)!]="";setCfg((x:any)=>({...x,storefront_media:next}))}

const section=tab===tabs[0]?<Editor title="بيانات التواصل" data={cfg.contact} fields={[["phone","رقم الهاتف"],["whatsapp","رقم واتساب بدون +"],["telegram","تيليغرام"],["facebook","رابط فيسبوك"],["email","الإيميل"]]} onChange={v=>setCfg(x=>({...x,contact:v}))} onSave={()=>save("contact")}/>:tab===tabs[1]?<StorefrontMediaEditor data={cfg.storefront_media||defaults.storefront_media} onChange={v=>setCfg(x=>({...x,storefront_media:v}))} onSave={()=>save("storefront_media")} upload={uploadStorefrontImage} deleteImage={deleteStorefrontImage}/>:tab===tabs[2]?<NoticesEditor items={cfg.storefront_notices||defaults.storefront_notices} onChange={items=>setCfg(x=>({...x,storefront_notices:items}))} onSave={()=>save("storefront_notices")}/>:tab===tabs[3]?<Editor title="التوصيل والشحن" data={cfg.delivery} fields={[["title","العنوان"],["intro","المقدمة"],["home","توصيل لباب المنزل"],["governorates","شحن المحافظات"],["note","ملاحظة"]]} onChange={v=>setCfg(x=>({...x,delivery:v}))} onSave={()=>save("delivery")}/>:tab===tabs[4]?<FAQEditor items={cfg.faq?.items||[]} onChange={items=>setCfg(x=>({...x,faq:{...x.faq,items}}))} onSave={()=>save("faq")}/>:tab===tabs[5]?<Editor title="الشروط والأحكام" data={cfg.terms} fields={[["title","العنوان"],["body","نص الشروط"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,terms:v}))} onSave={()=>save("terms")}/>:tab===tabs[6]?<Editor title="الاستبدال والاسترجاع" data={cfg.returns} fields={[["title","العنوان"],["body","نص السياسة"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,returns:v}))} onSave={()=>save("returns")}/>:tab===tabs[7]?<Editor title="سياسة الخصوصية" data={cfg.privacy} fields={[["title","العنوان"],["body","نص السياسة"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,privacy:v}))} onSave={()=>save("privacy")}/>:tab===tabs[8]?<Editor title="الدفع" data={cfg.wallet_payment} fields={[["method","طرق الدفع المعتمدة"],["account_name","اسم حساب شام كاش"],["account_number","عنوان شام كاش"],["note","ملاحظة"]]} textAreaKeys={["note"]} onChange={v=>setCfg(x=>({...x,wallet_payment:v}))} onSave={()=>save("wallet_payment")}/>:tab===tabs[9]?<Editor title="شحن المحفظة" data={cfg.wallet_topup} fields={[["title","العنوان"],["note","التعليمات"]]} textAreaKeys={["note"]} onChange={v=>setCfg(x=>({...x,wallet_topup:v}))} onSave={()=>save("wallet_topup")}/>:<Editor title="النقاط والإحالة" data={cfg.rewards} fields={[["points_per_dollar","نقاط لكل $"],["referrer_points","نقاط صاحب الإحالة"],["new_user_points","نقاط المستخدم الجديد"],["redemption_note","ملاحظة الاستبدال"]]} numberKeys={["points_per_dollar","referrer_points","new_user_points"]} textAreaKeys={["redemption_note"]} onChange={v=>setCfg(x=>({...x,rewards:v}))} onSave={()=>save("rewards")} checkbox={true}/>;
return <div className="space-y-5" dir="rtl"><div><p className="text-xs font-bold text-blue">IBRAHIM BAKKARI • STORE</p><h1 className="gold-shine text-2xl font-bold">إعدادات المتجر</h1></div><div className="flex gap-2 overflow-x-auto rounded-2xl bg-surface p-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-bold ${tab===t?"bg-white text-blue shadow-sm":"text-ink-soft"}`}>{t}</button>)}</div>{loading?<p className="text-sm text-ink-soft">جاري تحميل الإعدادات...</p>:<>{section}{msg&&<p className="text-xs text-ink-soft">{msg}</p>}</>}</div>}
function NoticesEditor({items,onChange,onSave}:{items:any[];onChange:(v:any[])=>void;onSave:()=>void}){const rows=Array.isArray(items)?items:[];const set=(i:number,k:string,v:string)=>onChange(rows.map((x:any,n:number)=>n===i?{...x,[k]:v}:x));const add=()=>onChange([...rows,{id:Date.now(),title:"ملاحظة جديدة",text:"اكتب الملاحظة التي تريد ظهورها أعلى المتجر.",icon:"ℹ️"}]);const remove=(i:number)=>onChange(rows.filter((_,n)=>n!==i));return <section className="admin-card" dir="rtl"><div><p className="section-kicker">STORE ANNOUNCEMENTS</p><h2>شريط إعلانات المتجر</h2><p className="mt-1 text-xs text-ink-soft">الإعلانات تظهر كشريط متحرك مستمر في أعلى المتجر، بدون بطاقات أو مستطيلات. يمكنك تعديلها أو إضافة ملاحظات جديدة.</p></div><div className="mt-5 space-y-3">{rows.map((x:any,i:number)=><div key={x.id||i} className="rounded-2xl border border-line bg-surface p-4"><div className="grid gap-3 sm:grid-cols-[80px_1fr_1.5fr]"><input value={x.icon||""} onChange={e=>set(i,"icon",e.target.value)} className="rounded-xl border border-line bg-white px-3 py-2.5 text-center text-lg" placeholder="ℹ️"/><input value={x.title||""} onChange={e=>set(i,"title",e.target.value)} className="rounded-xl border border-line bg-white px-3 py-2.5 text-sm" placeholder="عنوان الإعلان"/><input value={x.text||""} onChange={e=>set(i,"text",e.target.value)} className="rounded-xl border border-line bg-white px-3 py-2.5 text-sm" placeholder="نص الإعلان"/></div><button onClick={()=>remove(i)} className="mt-3 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs font-bold text-red-600">حذف الإعلان</button></div>)}</div><div className="mt-4 flex gap-2"><button onClick={add} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-bold">+ إضافة إعلان</button><button onClick={onSave} className="rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white">حفظ الإعلانات</button></div></section>}

function StorefrontMediaEditor({data,onChange,onSave,upload,deleteImage}:{data:any;onChange:(v:any)=>void;onSave:()=>void;upload:(file:File,current:any,setter:(v:any)=>void)=>Promise<string>;deleteImage:(path:string)=>Promise<void>}){
 const [uploading,setUploading]=useState(false); const [progress,setProgress]=useState(0); const [uploadLabel,setUploadLabel]=useState(""); const [saving,setSaving]=useState(false);
 const set=(path:string,value:string)=>{const next=structuredClone(data||{});let cur=next;const parts=path.split('.');for(let i=0;i<parts.length-1;i++){cur[parts[i]]=cur[parts[i]]||{};cur=cur[parts[i]]}cur[parts.at(-1)!]=value;onChange(next)};
 const pick=async(path:string)=>{const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/avif';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;setUploading(true);setProgress(0);setUploadLabel(file.name);try{const fd=new FormData();fd.append('file',file);const url=await new Promise<string>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/admin/digital-images');xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>{let j:any={};try{j=JSON.parse(xhr.responseText||'{}')}catch{};if(xhr.status>=200&&xhr.status<300&&j.url)resolve(j.url);else reject(new Error(j.error||'تعذر رفع الصورة'))};xhr.onerror=()=>reject(new Error('تعذر الاتصال بالخادم أثناء رفع الصورة'));xhr.send(fd)});set(path,url)}catch(e){alert(e instanceof Error?e.message:'تعذر رفع الصورة')}finally{setUploading(false);setUploadLabel('')}};input.click()};
 const psf=data.playstation_filters||{};
 const brands=['Apple','ASUS','Lenovo','Dell','HP','Acer','MSI','Microsoft','Samsung','LG','Razer','Huawei','Gigabyte','Alienware','Toshiba','VAIO','Dynabook','Xiaomi','Framework','Chuwi','Medion'];
 const groups=[
  {title:'🖼️ السلايدر الرئيسي',note:'صور البانرات الرئيسية — 1600 × 700 px',items:Array.from({length:5},(_,i)=>({path:`hero.${i}`,label:`السلايدر ${i+1}`,url:String((Array.isArray(data.hero)?data.hero:[])[i]||defaults.storefront_media.hero[i]||"")}))},
  {title:'💻 شعارات شركات اللابتوبات',note:'دوائر الشركات في الرئيسية وصفحة اللابتوبات — يفضّل 600 × 600 px بخلفية شفافة أو بيضاء',items:brands.map(k=>({path:`laptop_brand_logos.${k}`,label:k,url:String((data.laptop_brand_logos||{})[k]||DEFAULT_LAPTOP_BRAND_LOGOS[k]||'')}))},
  {title:'🎮 دوائر PlayStation',note:'600 × 600 px — بدون دائرة «الكل»',items:[['ps4','PS4'],['ps5','PS5'],['ps4-controller','قبضة PS4'],['ps5-controller','قبضة PS5']].map(([k,l])=>({path:`playstation_filters.${k}`,label:l,url:String(psf[k]||(defaults.storefront_media.playstation_filters as Record<string,string>)[k])}))},
  {title:'🗂️ صور أقسام المتجر',note:'600 × 600 px',items:Object.entries(data.categories||{}).map(([k,v])=>({path:`categories.${k}`,label:String(({business:'لابتوبات للأعمال',gaming:'لابتوبات Gaming',desktop:'كمبيوتر مكتبي',playstation:'PlayStation',digital:'الألعاب والخدمات الرقمية',accessories:'الإكسسوارات',web:'تصميم وبرمجة المواقع',offers:'العروض'} as any)[k]||k),url:String(v)}))},
  {title:'📣 البطاقات الترويجية',note:'1200 × 700 px',items:Object.entries(data.promos||{}).map(([k,v])=>({path:`promos.${k}`,label:k,url:String(v)}))},
  {title:'🧩 صور الأقسام الإضافية',note:'صور بانر خاصة بالأقسام',items:[{path:'playstation',label:'بانر PlayStation',url:data.playstation},{path:'pc_builder',label:'PC Builder',url:data.pc_builder}]},
 ];
 const saveNow=async()=>{setSaving(true);try{await onSave()}finally{setSaving(false)}};
 const renderCard=(c:any)=><div key={c.path} className="overflow-hidden rounded-2xl border border-line bg-surface"><div className="h-32 bg-white">{c.url?<img src={c.url} alt="" className="h-full w-full object-contain"/>:<div className="flex h-full items-center justify-center text-xs text-ink-soft">لا توجد صورة — استخدم الافتراضي</div>}</div><div className="p-3"><b className="block text-sm">{c.label}</b><span className="mt-1 block text-[10px] font-bold text-blue">{c.path.startsWith('laptop_brand_logos')?'600 × 600 px':c.path.startsWith('hero')?'1600 × 700 px':c.path.startsWith('playstation_filters')?'600 × 600 px':'المقاس حسب الصورة'}</span><button disabled={uploading} onClick={()=>void pick(c.path)} className="mt-3 w-full rounded-xl bg-blue px-3 py-2.5 text-xs font-bold text-white">{uploading&&uploadLabel?`جاري رفع ${uploadLabel}`:'📸 تغيير الصورة'}</button>{c.url&&<button disabled={uploading} onClick={()=>{if(confirm('حذف هذه الصورة؟'))void deleteImage(c.path)}} className="mt-2 w-full rounded-xl border border-red-200 bg-red-50 px-3 py-2.5 text-xs font-bold text-red-600">🗑️ حذف</button>}</div></div>;
 return <section className="admin-card" dir="rtl"><div><p className="section-kicker">STOREFRONT MEDIA</p><h2>صور واجهة المتجر</h2><p className="mt-1 text-xs text-ink-soft">مرتبة ضمن مجموعات حتى تلاقي الصورة المطلوبة بسرعة وتعرف مكان استخدامها ومقاسها.</p></div>{groups.map(g=><div key={g.title} className="mt-6"><div className="mb-3"><h3 className="text-lg font-extrabold">{g.title}</h3><p className="mt-1 text-xs text-ink-soft">{g.note}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{g.items.map(renderCard)}</div></div>)}{uploading&&<div className="mt-5 rounded-2xl border border-blue/20 bg-blue/5 p-4"><div className="flex items-center justify-between text-xs font-bold"><span>جاري رفع الصورة: {uploadLabel}</span><b>{progress}%</b></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue transition-all" style={{width:`${progress}%`}}/></div></div>}<button disabled={saving} onClick={()=>void saveNow()} className="mt-6 rounded-xl bg-blue px-5 py-3 text-xs font-bold text-white">{saving?'⏳ جاري الحفظ...':'✓ حفظ إعدادات الصور'}</button></section>
}

function Editor({title,data,fields,onChange,onSave,textAreaKeys=[],numberKeys=[],extra,checkbox}:{title:string;data:any;fields:string[][];onChange:(v:any)=>void;onSave:()=>void;textAreaKeys?:string[];numberKeys?:string[];extra?:ReactNode;checkbox?:boolean}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className="block text-xs font-bold sm:col-span-1">{label}{textAreaKeys.includes(key)?<textarea rows={7} value={data?.[key]??""} onChange={e=>onChange({...data,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-line bg-surface p-3 leading-7"/>:<input type={numberKeys.includes(key)?"number":"text"} value={data?.[key]??""} onChange={e=>onChange({...data,[key]:numberKeys.includes(key)?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border border-line bg-surface p-3"/>}</label>)}</div>{checkbox&&<label className="mt-3 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!data?.enabled} onChange={e=>onChange({...data,enabled:e.target.checked})}/> تفعيل نظام النقاط</label>}{extra}<button onClick={onSave} className="mt-4 rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white">حفظ التعديلات</button></section>}
function FAQEditor({items,onChange,onSave}:{items:any[];onChange:(v:any[])=>void;onSave:()=>void}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="font-bold">الأسئلة الشائعة</h2><div className="mt-4 space-y-4">{items.map((x,i)=><div key={i} className="rounded-xl bg-surface p-4"><input value={x.q||""} onChange={e=>{const n=[...items];n[i]={...n[i],q:e.target.value};onChange(n)}} placeholder="السؤال" className="w-full rounded-xl border border-line bg-white p-3 text-sm"/><textarea value={x.a||""} onChange={e=>{const n=[...items];n[i]={...n[i],a:e.target.value};onChange(n)}} placeholder="الجواب" rows={3} className="mt-2 w-full rounded-xl border border-line bg-white p-3 text-sm"/><button onClick={()=>onChange(items.filter((_,j)=>j!==i))} className="mt-2 text-xs font-bold text-red-500">حذف السؤال</button></div>)}</div><div className="mt-4 flex gap-2"><button onClick={()=>onChange([...items,{q:"",a:""}])} className="rounded-xl border border-line px-4 py-2.5 text-xs font-bold">+ سؤال</button><button onClick={onSave} className="rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white">حفظ الأسئلة</button></div></section>}
