"use client";
import {useEffect,useState} from "react";
import type { ReactNode } from "react";
import {createClient} from "@/app/lib/supabase-browser";

type AnySettings=Record<string,any>;
const defaults={
 contact:{phone:"0936426605",whatsapp:"963936426605",telegram:"@NexCode9",facebook:"https://www.facebook.com/share/1BZU7LUd2o/",email:"ibrahimbkkari51@gmail.com"},
 delivery:{title:"التوصيل والشحن",intro:"منوصل طلباتك لباب المنزل، والشحن متاح للمحافظات السورية حسب المحافظة.",home:"توصيل لباب المنزل — مننسق معك العنوان قبل التسليم.",governorates:"شحن لكل المحافظات الفعالة بالموقع، وتكلفة الشحن ومدة الوصول بتختلف حسب المحافظة.",note:"للطلبات الكبيرة أو خدمات البرمجة، مننسق التفاصيل معك بشكل مباشر."},
 terms:{title:"الشروط والأحكام",body:"باستخدام Bkkari Tech، يوافق المستخدم على تقديم معلومات صحيحة عند إنشاء الحساب أو الطلب، وعلى مراجعة تفاصيل المنتج والسعر قبل تأكيد الطلب."},
 returns:{title:"الاستبدال والاسترجاع",body:"يتم فحص طلبات الاستبدال والاسترجاع حسب حالة المنتج وسبب الطلب. يجب التواصل مع الدعم بأسرع وقت عند وجود مشكلة أو عيب."},
 privacy:{title:"سياسة الخصوصية",body:"نستخدم معلومات الحساب والطلب مثل الاسم والبريد ورقم الهاتف والعنوان لتنفيذ الطلب والتواصل مع العميل."},
 faq:{items:[{q:"كيف بطلب لابتوب؟",a:"اختار الجهاز وأضفه للسلة وكمل بيانات الطلب."},{q:"كيف بيصير التوصيل؟",a:"مننسق معك العنوان وتفاصيل الشحن حسب المحافظة."},{q:"كيف بتتبع طلبي؟",a:"من صفحة تتبع الطلب أدخل رقم الطلب ورقم الهاتف."}]},
 wallet_payment:{method:"الدفع عند الاستلام أو المحفظة",account_name:"",account_number:"",image_url:"",note:"طرق الدفع المتاحة: المحفظة أو الدفع عند الاستلام."},
 wallet_topup:{mode:"direct_contact",title:"شحن مباشر للمحفظة",note:"لشحن المحفظة، تواصل مع الإدارة عبر واتساب أو الدعم."},
 rewards:{enabled:true,points_per_dollar:1,referrer_points:100,new_user_points:50,redemption_note:"كل 100 نقطة = 1$ رصيد خصم عند تطبيق النظام من الإدارة."}
};
const tabs=["التواصل","الشحن","الأسئلة الشائعة","الشروط","الاستبدال","الخصوصية","الدفع","شحن المحفظة","النقاط"] as const;
export default function SettingsPage(){const s=createClient();const [tab,setTab]=useState<typeof tabs[number]>("التواصل");const [cfg,setCfg]=useState<AnySettings>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState("");
useEffect(()=>{fetch("/api/admin/site-settings").then(r=>r.json()).then(j=>setCfg(x=>({...x,...j.settings}))).finally(()=>setLoading(false))},[]);
async function save(key:string){setSaving(true);setMsg("");const r=await fetch("/api/admin/site-settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key,value:cfg[key]})});setSaving(false);setMsg(r.ok?"تم الحفظ ✓":(await r.json()).error||"تعذر الحفظ")}
async function uploadPayment(file:File){const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`shamcash-${Date.now()}.${ext}`;const up=await s.storage.from("payment-assets").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMsg("تعذر رفع الصورة. تأكد من صلاحيات bucket الدفع.");return}const {data}=s.storage.from("payment-assets").getPublicUrl(path);setCfg((x:any)=>({...x,wallet_payment:{...x.wallet_payment,image_url:data.publicUrl}}));}
const section=tab===tabs[0]?<Editor title="بيانات التواصل" data={cfg.contact} fields={[["phone","رقم الهاتف"],["whatsapp","رقم واتساب بدون +"],["telegram","تيليغرام"],["facebook","رابط فيسبوك"],["email","الإيميل"]]} onChange={v=>setCfg(x=>({...x,contact:v}))} onSave={()=>save("contact")}/>:tab===tabs[1]?<Editor title="التوصيل والشحن" data={cfg.delivery} fields={[["title","العنوان"],["intro","المقدمة"],["home","توصيل لباب المنزل"],["governorates","شحن المحافظات"],["note","ملاحظة"]]} onChange={v=>setCfg(x=>({...x,delivery:v}))} onSave={()=>save("delivery")}/>:tab===tabs[2]?<FAQEditor items={cfg.faq?.items||[]} onChange={items=>setCfg(x=>({...x,faq:{...x.faq,items}}))} onSave={()=>save("faq")}/>:tab===tabs[3]?<Editor title="الشروط والأحكام" data={cfg.terms} fields={[["title","العنوان"],["body","نص الشروط"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,terms:v}))} onSave={()=>save("terms")}/>:tab===tabs[4]?<Editor title="الاستبدال والاسترجاع" data={cfg.returns} fields={[["title","العنوان"],["body","نص السياسة"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,returns:v}))} onSave={()=>save("returns")}/>:tab===tabs[5]?<Editor title="سياسة الخصوصية" data={cfg.privacy} fields={[["title","العنوان"],["body","نص السياسة"]]} textAreaKeys={["body"]} onChange={v=>setCfg(x=>({...x,privacy:v}))} onSave={()=>save("privacy")}/>:tab===tabs[6]?<Editor title="الدفع" data={cfg.wallet_payment} fields={[["method","طرق الدفع المعتمدة"],["account_name","اسم حساب شام كاش"],["account_number","عنوان شام كاش"],["note","ملاحظة"]]} textAreaKeys={["note"]} onChange={v=>setCfg(x=>({...x,wallet_payment:v}))} onSave={()=>save("wallet_payment")}/>:tab===tabs[7]?<Editor title="شحن المحفظة" data={cfg.wallet_topup} fields={[["title","العنوان"],["note","التعليمات"]]} textAreaKeys={["note"]} onChange={v=>setCfg(x=>({...x,wallet_topup:v}))} onSave={()=>save("wallet_topup")}/>:<Editor title="النقاط والإحالة" data={cfg.rewards} fields={[["points_per_dollar","نقاط لكل $"],["referrer_points","نقاط صاحب الإحالة"],["new_user_points","نقاط المستخدم الجديد"],["redemption_note","ملاحظة الاستبدال"]]} numberKeys={["points_per_dollar","referrer_points","new_user_points"]} textAreaKeys={["redemption_note"]} onChange={v=>setCfg(x=>({...x,rewards:v}))} onSave={()=>save("rewards")} checkbox={true}/>;
return <div className="space-y-5" dir="rtl"><div><p className="text-xs font-bold text-blue">IBRAHIM BAKKARI • STORE</p><h1 className="gold-shine text-2xl font-bold">إعدادات المتجر</h1></div><div className="flex gap-2 overflow-x-auto rounded-2xl bg-surface p-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 rounded-xl px-4 py-2.5 text-xs font-bold ${tab===t?"bg-white text-blue shadow-sm":"text-ink-soft"}`}>{t}</button>)}</div>{loading?<p className="text-sm text-ink-soft">جاري تحميل الإعدادات...</p>:<>{section}{msg&&<p className="text-xs text-ink-soft">{msg}</p>}</>}</div>}
function Editor({title,data,fields,onChange,onSave,textAreaKeys=[],numberKeys=[],extra,checkbox}:{title:string;data:any;fields:string[][];onChange:(v:any)=>void;onSave:()=>void;textAreaKeys?:string[];numberKeys?:string[];extra?:ReactNode;checkbox?:boolean}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className="block text-xs font-bold sm:col-span-1">{label}{textAreaKeys.includes(key)?<textarea rows={7} value={data?.[key]??""} onChange={e=>onChange({...data,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-line bg-surface p-3 leading-7"/>:<input type={numberKeys.includes(key)?"number":"text"} value={data?.[key]??""} onChange={e=>onChange({...data,[key]:numberKeys.includes(key)?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border border-line bg-surface p-3"/>}</label>)}</div>{checkbox&&<label className="mt-3 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={!!data?.enabled} onChange={e=>onChange({...data,enabled:e.target.checked})}/> تفعيل نظام النقاط</label>}{extra}<button onClick={onSave} className="mt-4 rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white">حفظ التعديلات</button></section>}
function FAQEditor({items,onChange,onSave}:{items:any[];onChange:(v:any[])=>void;onSave:()=>void}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="font-bold">الأسئلة الشائعة</h2><div className="mt-4 space-y-4">{items.map((x,i)=><div key={i} className="rounded-xl bg-surface p-4"><input value={x.q||""} onChange={e=>{const n=[...items];n[i]={...n[i],q:e.target.value};onChange(n)}} placeholder="السؤال" className="w-full rounded-xl border border-line bg-white p-3 text-sm"/><textarea value={x.a||""} onChange={e=>{const n=[...items];n[i]={...n[i],a:e.target.value};onChange(n)}} placeholder="الجواب" rows={3} className="mt-2 w-full rounded-xl border border-line bg-white p-3 text-sm"/><button onClick={()=>onChange(items.filter((_,j)=>j!==i))} className="mt-2 text-xs font-bold text-red-500">حذف السؤال</button></div>)}</div><div className="mt-4 flex gap-2"><button onClick={()=>onChange([...items,{q:"",a:""}])} className="rounded-xl border border-line px-4 py-2.5 text-xs font-bold">+ سؤال</button><button onClick={onSave} className="rounded-xl bg-blue px-5 py-2.5 text-xs font-bold text-white">حفظ الأسئلة</button></div></section>}
